openapi: "3.0.1"
info:
  title: "HuBMAP Spatial API"
  description: "The HuBMAP Spatial API is a standard RESTful web service with create\
    \ operations."
  version: "1.0.0"
servers:
- url: "https://spatial-api.dev.hubmapconsortium.org"
paths:
  /search/hubmap_id/{hubmap_id}/radius/{radius}/target/{target}:
    get:
      operationId: "search_hubmap_id_to_radius"
      parameters:
      - name: "target"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "radius"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "hubmap_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "400":
          description: "400 response"
          content: {}
        "404":
          description: "404 response"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HubMAPIds"
      x-amazon-apigateway-integration:
        type: "http"
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "GET"
        uri: "http://${stageVariables.VPCNLB}/search/hubmap_id/{hubmap_id}/radius/{radius}/target/{target}"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.hubmap_id: "method.request.path.hubmap_id"
          integration.request.path.radius: "method.request.path.radius"
          integration.request.path.target: "method.request.path.target"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
  /spatial-search/point:
    post:
      operationId: "spatial_search_point"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpatialSearchPointRequest"
        required: true
      responses:
        "400":
          description: "400 response"
          content: {}
        "404":
          description: "404 response"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HubMAPIds"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "POST"
        uri: "http://${stageVariables.VPCNLB}/spatial-search/point"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
  /spatial-search/hubmap_id:
    post:
      operationId: "spatial_search_hubmap_id"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpatialSearchRequest"
        required: true
      responses:
        "400":
          description: "400 response"
          content: {}
        "404":
          description: "404 response"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HubMAPIds"
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "POST"
        uri: "http://${stageVariables.VPCNLB}/spatial-search/hubmap_id"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
components:
  schemas:
    SpatialSearchPointRequest:
      type: "object"
      properties:
        target:
          type: "string"
        radius:
          type: "number"
        x:
          type: "number"
        y:
          type: "number"
        z:
          type: "number"
    SpatialSearchRequest:
      type: "object"
      properties:
        target:
          type: "string"
        radius:
          type: "number"
        hubmap_id:
          type: "string"
        cell_type:
          type: "string"
    HubMAPIds:
      type: "object"
      properties:
        hubmap_ids:
          type: "array"
          description: "List of HubMAP IDs."
          items:
            type: "string"
