openapi: "3.0.1"
info:
  title: "HuBMAP Spatial API"
  description: "The HuBMAP Spatial API is a standard RESTful web service with create\
    \ operations."
  version: "1.0.0"
servers:
- url: "https://spatial-api.dev.hubmapconsortium.org"
paths:
  /status:
    get:
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "GET"
        uri: "http://${stageVariables.VPCNLB}/status"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
  /search/hubmap-id/{id}/radius/{radius}/target/{target}:
    get:
      parameters:
      - name: "target"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "radius"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "GET"
        uri: "http://${stageVariables.VPCNLB}/search/hubmap-id/{id}/radius/{radius}/target/{target}"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.id: "method.request.path.id"
          integration.request.path.radius: "method.request.path.radius"
          integration.request.path.target: "method.request.path.target"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http"
  /db/rebuild/annotation-details:
    put:
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "PUT"
        uri: "http://${stageVariables.VPCNLB}/db/rebuild/annotation-details"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
  /spatial-search/point:
    post:
      operationId: "spatial_search_point"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpatialSearchPointRequest"
        required: true
      responses:
        "400":
          description: "400 response"
          content: {}
        "404":
          description: "404 response"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HubMAPIds"
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "POST"
        uri: "http://${stageVariables.VPCNLB}/spatial-search/point"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
  /sample/begin-extract-cell-type-counts-for-all-samples-for-organ-code:
    put:
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "PUT"
        uri: "http://${stageVariables.VPCNLB}/sample/begin-extract-cell-type-counts-for-all-samples-for-organ-code"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
  /db/rebuild/organ-sample-data:
    put:
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "PUT"
        uri: "http://${stageVariables.VPCNLB}/db/rebuild/organ-sample-data"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
  /spatial-search/hubmap-id:
    post:
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "POST"
        uri: "http://${stageVariables.VPCNLB}/spatial-search/hubmap-id"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
  /sample/begin-extract-cell-type-counts-for/sample-uuid/{uuid}:
    put:
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        schema:
          type: "string"
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "PUT"
        uri: "http://${stageVariables.VPCNLB}/sample/begin-extract-cell-type-counts-for/sample-uuid/{uuid}"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.uuid: "method.request.path.uuid"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
  /sample/extracted-cell-type-counts-from-secondary-analysis-files:
    put:
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "PUT"
        uri: "http://${stageVariables.VPCNLB}/sample/extracted-cell-type-counts-from-secondary-analysis-files"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
  /:
    get:
      x-amazon-apigateway-integration:
        connectionId: "${stageVariables.VPCLINK}"
        httpMethod: "GET"
        uri: "http://${stageVariables.VPCNLB}/"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        type: "http_proxy"
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:450834107946:function:HuBMAP-API-Gateway-404/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
components:
  schemas:
    SpatialSearchPointRequest:
      type: "object"
      properties:
        target:
          type: "string"
        radius:
          type: "number"
        x:
          type: "number"
        y:
          type: "number"
        z:
          type: "number"
    HubMAPIds:
      type: "object"
      properties:
        hubmap_ids:
          type: "array"
          description: "List of HubMAP IDs."
          items:
            type: "string"
